DROP TABLE artwork_exhibitions CASCADE;
DROP TABLE artworks CASCADE;
DROP TABLE exhibitions CASCADE;
DROP TABLE exhibition_halls CASCADE;
DROP TABLE owners CASCADE;
DROP TABLE artists CASCADE;
DROP TABLE execution_types CASCADE;
DROP TABLE owner_types CASCADE;
DROP TABLE exhibition_types CASCADE;
